language: bash

# for secret experimental features ;)
sudo: 9000

env:
  - VERSION=1.8-rc
  - VERSION=1.7
  - VERSION=1.6
  - VERSION=1.5
  - VERSION=1.4
  - VERSION=1.3
  - VERSION=1.2
  - VERSION=1.1
  - VERSION=1.0

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="docker:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - docker build -t "$image-dind" dind
  - ~/official-images/test/run.sh "$image-dind"
  - docker build -t "$image-git" git
  - ~/official-images/test/run.sh "$image-git"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
