language: bash
services: docker

env:
  - VERSION=17.03 VARIANT=
  - VERSION=1.13 VARIANT=

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${VERSION}${VARIANT:+/$VARIANT}"
  - image="docker:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - travis_retry docker build -t "$image-dind" dind
  - ~/official-images/test/run.sh "$image-dind"
  - travis_retry docker build -t "$image-git" git
  - ~/official-images/test/run.sh "$image-git"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
